### ISSUE TITLE
Pogrešna pretpostavka

### ISSUE THREAD

**Issue by dusandevic** [Vlasterx/test-samostalnosti#2]
Odličan tekst! Primetio si nekoliko jako bitnih detalja koji su nam promakli. Mislim da imaš jednu pogrešnu pretpostavku a to je da su Uputstvo pisali ljudi koji nemaju dodirnih tačaka sa IT-em. Uputstvo su pisali ljudi koji su pravne struke uz konsultacije ovih što veoma dobro razumeju IT, ali je napisano na ovaj način jer je maliciozno i zlonamerno.

**Comment by Vlasterx** [comment]
Sudeći po sadržaju teksta, utisak je da su pisali nestručni ljudi. Ukoliko to nije tačna pretpostavka, onda je malicioznost sa njihove strane više nego očigledna.
